/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_emery_bspath_FileDiffAndPathUtils */

#ifndef _Included_com_example_emery_bspath_FileDiffAndPathUtils
#define _Included_com_example_emery_bspath_FileDiffAndPathUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_emery_bspath_FileDiffAndPathUtils
 * Method:    bisDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_emery_bspath_FileDiffAndPathUtils_bisDiff
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_example_emery_bspath_FileDiffAndPathUtils
 * Method:    bisPath
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_emery_bspath_FileDiffAndPathUtils_bisPath
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
